name: Build and Lint Game
on:
  pull_request: 
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  build-and-lint:
    name: 'Build and Lint Game'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ['./tests/games/basic']
      
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.10.0

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Prettier
        run: pnpm prettier

      - name: Linting
        run: pnpm lint

      - name: Building
        run: pnpm build